<?php

namespace logic\rbac\validation;

use app\model\rbac_role;
use pms\Validation;

/**
 * 角色增加的验证器
 * Class AddRole
 * @package logic\rbac\validation
 */
class AddRole extends Validation
{
    protected function initialize()
    {
        # 判断是否存在
        $this->add_exist('role_id', [
            'message' => 'exist',
            'class_name_list' => rbac_role::class,
        ]);
        $this->add_exist('uid', [
            'message' => 'exist',
            'class_name_list' => \app\model\User::class
        ]);
        $this->add_exist('uid', [
            'message' => 'exist',
            'class_name_list' => \app\model\User::class
        ]);

        $this->add_Validator('role_id', [
            'name' => rbac_role_relation_add::class,
            'message' => 'user_role_relation_add'
        ]);
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

}