<?php

namespace app\validation;

use app\model\rbac_role;
use app\model\rbac_rule_auth;
use app\validator\rbac_role_del;


/**
 * 删除角色 的 验证器
 * Class del_role
 * @package logic\user\validation
 */
class del_role extends \pms\Validation
{

    protected $lang = 'admin/model/user.php';
    protected $lang_field_prefix = 'model-user_resources-field';
    protected $rules = [
        'id' => [
            #验证存在
            'exist' => [
                'message' => 'exist',
                'class_name_list' => \app\model\rbac_role::class
            ],
            #验证引用
            'correlation' => [
                'message' => 'message',
                'model_list' => [
                    rbac_role::class,
                    rbac_rule_auth::class
                ],
                'fields_name' => [
                    'pid',
                    'role'
                ]
            ]

        ],
    ];

    protected function initialize()
    {


        $this->add_Validator('id', [
            'name' => rbac_role_del::class,
            'message' => 'can_del'
        ]);


        return parent::initialize(); // TODO: Change the autogenerated stub
    }
}